### ISSUE TITLE
“文章”首页的卡片不能正确显示链接

### ISSUE THREAD

**Issue by YDX-2147483647** [BIT101-dev/BIT101#2]
如题。

请看下图，链接被显示成了 HTML。

![image](https://user-images.githubusercontent.com/73375426/183700409-891a2a07-4899-4f50-9835-5db793e60996.png)

https://github.com/BIT101-dev/BIT101/blob/f0420b6c18869c2fe912287afbea742edacda7ef/src/views/PaperEdit.vue#L169-L182

**Comment by flwfdd** [comment]
看来去富文本化还是不够干净2333（可以先暂时手动更改简介予以解决

**Comment by YDX-2147483647** [comment]
有道理，已改。最后还是半个标签呢。
