### ISSUE TITLE
[Bug] 无法删除开启匿名后发表的评论

### ISSUE THREAD

**Issue by rinevard** [BIT101-dev/BIT101#35]
![test](https://github.com/BIT101-dev/BIT101/assets/136295900/ce7426db-182a-41b4-99b3-10465d3577ae)

**Comment by flwfdd** [comment]
乐 之前为了处理匿名马甲引入了一个“未登录会显示匿名评论可删除”的bug 中午修复后又引入了这个bug bug级联裂变了属于是

**Comment by flwfdd** [comment]
https://github.com/BIT101-dev/BIT101-GO/commit/bf061a84d07bead3778465bd9b7c4c1c1f6a7f70
