### ISSUE TITLE
在 NFS  + yarn 的场景下，安装包过程长达数十分钟

### ISSUE THREAD

**Issue by leookun** [BIT101-dev/BIT101#39]
我发现这是很多图标文件导致的，如果同时安装了几个@vicons 下的图标库，node_modules 中需要拷贝或者解压的文件超过了几万个
使用网络共享磁盘的情况下表现的非常缓慢，甚至超时，例如：
https://github.com/yarnpkg/yarn/pull/8363
如果把图标放到一个文件中，依靠外部项目自身的tree shaking是不是一个更好的办法？

**Comment by Dustin-Jiang** [comment]
首先yarn的性能就不咋地，而NFS加剧了性能灾难。`@vicons`的这个问题存在很久了，不仅是安装效率问题，在调试时也会导致debugger卡死。在 https://github.com/07akioni/xicons/issues/420 中也提到了这方面的问题。
