### ISSUE TITLE
潜在的COS盗刷风险等安全风险

### ISSUE THREAD

**Issue by cxw620** [BIT101-dev/BIT101#7]
看了看后端代码, 简单挖掘了一下信息, 发现了一些小问题. 要持久做下去这些问题我觉得得解决.

首先是COS的存储桶名泄露. 这玩意就算你设置不可匿名访问, 别人也可以直接访问刷API请求数, 这个也是计费的. 避免别人搞事情最好隐去. 泄露的存储桶名称是bit101-1255944436, bit101-test-1255944436. 1255944436是账户ID. 此外, 阿里云OSS也泄露了一个: flw***.oss-cn-hangzhou.aliyuncs.com

其次COS没上请求限频, 例如https://bit101-1255944436.cos.ap-beijing.myqcloud.com/img/fd562e5030ad533d7cdc3d70a6ee76a1.png这个静态文件3.2MB, 被盗刷分分钟底裤都给赔上去. 最好上CDN配置请求限频

再有, 后端IP没做隐藏(101.*.*.210), MySQL也暴露在公网(3306). 延伸到个人博客站点也暴露了公网IP(118.*.*.247)及若干端口. 为了降低安全风险最好隐藏. 这属于网安相关, 可找网安的熟人协助测试排查更多可能存在的安全风险, 我不是这个专业了解不多, 仅作了浅显分析.

最后, OneDrive的client_id和client_secret也写在了代码里, 这玩意被脚本扫描到后可能被他人盗用, 滥用API世纪互联是会封号的. 最好写入config里

感谢大佬的贡献~ 实用的网站, Mark了, 希望长久运营下去

**Comment by flwfdd** [comment]
对象存储配置自定义域名都要求用备案域名，所以就还是先这样吧。我开了监控报警，余额也不多，盗刷流量的风险应该还是比较可控的....？
后端数据库确实，因为这段时间直连调试比较多就没有关，之后我会注意的。但是后端IP怎么隐藏我确实没什么思路....这是可以做到的吗....还望不吝赐教。
OneDrive直接用的 @spencerwooo 的项目，那玩意儿泄露了问题应该也不是很大，真正起作用的是一个 refresh_token ，这个不会暴露的，况且这号本来就是滥用了（笑）（淘宝50买的），本来就是打算即用即抛。

总之还是非常感谢您提出的建议，可以加一下QQ群726965926♪(´▽｀)
