### ISSUE TITLE
[功能请求] 适配 PWA（渐进式 Web 应用）

### ISSUE THREAD

**Issue by FrzMtrsprt** [BIT101-dev/BIT101#9]
希望能在手机上方便地访问网站，但又不希望单独安装一个应用（~~主要是因为客户端的体验不是很好~~）。
如果适配 PWA 的话，就能一键将网站添加到主页，并使用浏览器的自动填充等各种便利，这样最好不过了。

PWA 的适配过程可以参考[这篇博客](https://www.nousbuild.org/codeu/website-with-pwa/)和文中的三篇官方介绍。

**Comment by flwfdd** [comment]
https://github.com/BIT101-dev/BIT101/commit/7860d6025774f91850984b5984e6f5db94ab0761
